name: QuantumHealing
favicon: null
layout_spectrum: 0
typography_spectrum: 0.98996
title: 'Pioneering the Art and Science of Personal WellNES Assurance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4599d3'
    - '#231f20'
    - '#ffffff'
    - '#ed2728'
    - '#f6987b'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
