name: QuantumHealing
favicon: null
layout_spectrum: 0.73996
typography_spectrum: 0.27344
title: 'Pioneering Personal WellNES Assurance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#999cd1'
    - '#000c00'
    - '#5b6453'
    - '#8c9e00'
    - '#b0cb05'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.8521503461524844
purpose: []
